class BasePrompt:
    SYSTEM_INSTRUCTION = (
        "You are an expert financial analyst. Your task is to extract structured facts "
        "from parsed document blocks. Extract ONLY facts explicitly supported by the text. "
        "DO NOT estimate, annualize, calculate, extrapolate, interpolate, reconcile, or compare values. "
        "For each fact, output it matching the required JSON schema structure.\n\n"
        "Strictly adhere to the following definitions:\n"
        "- confidence_reason MUST be one of: 'Structured Table', 'Explicit Sentence', 'Heading', 'Bullet List', 'Repeated Across Blocks'.\n"
        "- extraction_method MUST be one of: 'text', 'table', 'heading', 'list'.\n"
        "- status MUST be 'extracted'.\n\n"
        "Confidence rules:\n"
        "- Use 'Structured Table' if the value comes from an Excel sheet row, a CSV file, or a table on a slide/page.\n"
        "- Use 'Explicit Sentence' if it is stated directly in free text.\n"
        "- Use 'Heading' if it is in a section title.\n"
        "- Use 'Bullet List' if it is part of a list format."
    )

    @classmethod
    def build_extraction_prompt(cls, doc_prompt: str, registry_json: str, chunk_json: str) -> str:
        return (
            f"{doc_prompt}\n\n"
            f"EXPECTED FACTS REGISTRY (Do not extract facts outside this registry):\n"
            f"{registry_json}\n\n"
            f"PARSED DOCUMENT BLOCKS:\n"
            f"{chunk_json}\n\n"
            f"Output a JSON list of facts matching this JSON schema:\n"
            f"[\n"
            f"  {{\n"
            f"    \"fact_id\": \"(generate a unique stable ID based on block ID, e.g. fact_pitch_deck_01_0)\",\n"
            f"    \"category\": \"(matching category from registry, e.g. financial, traction, team, etc.)\",\n"
            f"    \"metric_name\": \"(matching metric name from registry, e.g. Revenue, Cash Balance, etc.)\",\n"
            f"    \"value\": (the raw numerical or text value, or null),\n"
            f"    \"display_value\": \"(the exact text string value as shown in the document)\",\n"
            f"    \"unit\": \"(e.g., $, %, headcount, shares)\",\n"
            f"    \"currency\": \"(e.g., USD, INR, or empty)\",\n"
            f"    \"period\": \"(e.g., FY2025, Jan 2025, or empty)\",\n"
            f"    \"fiscal_year\": \"(e.g., 2025, or empty)\",\n"
            f"    \"document_type\": \"(document type of the source block)\",\n"
            f"    \"source_document\": \"(name of the source file)\",\n"
            f"    \"source_block_id\": \"(the exact stable block ID from parsed data)\",\n"
            f"    \"page\": (page number or null),\n"
            f"    \"confidence\": (a percentage float, e.g., 95.0),\n"
            f"    \"confidence_reason\": \"(one of the 5 allowed reasons)\",\n"
            f"    \"extraction_method\": \"(one of the 4 allowed methods)\",\n"
            f"    \"status\": \"extracted\",\n"
            f"    \"context\": {{\n"
            f"      \"section\": \"(title of the section block falls under, if any)\",\n"
            f"      \"sentence\": \"(the exact sentence containing the metric/fact)\"\n"
            f"    }}\n"
            f"  }}\n"
            f"]\n\n"
            f"Ensure to strictly output ONLY valid JSON. No Markdown formatting or wrapping, just raw JSON."
        )
