# Central Version Registry
PIPELINE_VERSION: str = "1.0"
PROMPT_VERSION: str = "v1"
REGISTRY_VERSION: str = "1.0"
SCHEMA_VERSION: str = "1.0"
TEMPLATE_VERSION: str = "1.0"
COMPARISON_RULES_VERSION: str = "1.0"
READINESS_VERSION: str = "1.0"
